CREATE DATABASE crm;
USE crm;

DROP TABLE PURCHASE;
DROP TABLE CLIENT;
DROP TABLE CLIENTTYPE;
DROP TABLE ADMIN;
 CREATE TABLE CLIENTTYPE(
 id INT(10) PRIMARY KEY AUTO_INCREMENT,
 ctype VARCHAR(50) NOT NULL
 );

CREATE TABLE CLIENT(
 id INT(10) PRIMARY KEY,
  name VARCHAR(50),
  type INT(10),
   email VARCHAR(50),
   FOREIGN KEY (type) REFERENCES CLIENTTYPE(id)
);

CREATE TABLE PURCHASE(
 id INT(10) PRIMARY KEY AUTO_INCREMENT,
 client  INT(10) NOT NULL,
  date TIMESTAMP NOT NULL DEFAULT NOW(),
  totalValue INT(10) NOT NULL,
 FOREIGN KEY (client) REFERENCES CLIENT(id)
);


CREATE TABLE ADMIN(
  id INT(10) PRIMARY KEY,
  name VARCHAR(50),
  password VARCHAR(50)
 );


 INSERT INTO CLIENTTYPE(ctype) VALUES ('bueno');
 INSERT INTO CLIENTTYPE(ctype) VALUES ('malo');
 INSERT INTO CLIENT VALUES('1000000000','Mike Litoris', 1,'j@h');
 INSERT INTO PURCHASE(client, totalValue) VALUES('1000000000',10000);
 INSERT INTO PURCHASE(client, totalValue) VALUES('1000000000',20000);
 INSERT INTO ADMIN VALUES(0000000000,'root','root');