CREATE DATABASE crm;
USE crm;


 CREATE TABLE CLIENTTYPE(
 id INT(10) PRIMARY KEY AUTO_INCREMENT,
 ctype VARCHAR(50) NOT NULL
 );

CREATE TABLE CLIENT(
 id INT(10) PRIMARY KEY,
  name VARCHAR(50),
  type INT(10),
   email VARCHAR(50),
   FOREIGN KEY (type) REFERENCES CLIENTTYPE(id)
);

CREATE TABLE PURCHASE(
 id INT(10) PRIMARY KEY AUTO_INCREMENT,
 client  INT(10) NOT NULL,
  date DATE NOT NULL,
  totalValue INT(10) NOT NULL,
 FOREIGN KEY (client) REFERENCES CLIENT(id)
);


CREATE TABLE ADMIN(
  id INT(10) PRIMARY KEY,
  name VARCHAR(50),
  password VARCHAR(50)
 );

